### ISSUE TITLE
Two names where there should be one

### ISSUE THREAD

**Issue by OIIyE** [RichardMorris/SACDungeon#9]
James & Jamie are provided as names, where as it is the same person so they are included twice.
(Probably my fault as part of the previous merge, whoops!)

**Comment by RichardMorris** [comment]
Which file are we talking about, what line number.
WHich is the correct name.

**Comment by OIIyE** [comment]
> Which file are we talking about, what line number. Which is the correct name.

The file is README.md, with the Authors in question being James Lias and Jamie Lias under lines 28 and 31 respectively.

Will pass this off to @cynicaljman, on which name to decide upon.

**Comment by cynicaljman** [comment]
legally the name is James, not Jamie

**Comment by mrree1078** [comment]
Never fear the bug fixer is here!

**Comment by OIIyE** [comment]
> 

What's your callsign, oh majestic superhero?

**Comment by mrree1078** [comment]
mrree (mystery) so my alter ego is never known
